### ISSUE TITLE
Cleanup needed by most!!!

### ISSUE THREAD

**Issue by melanietimms** [Daruu88/tafe-online-learning#10]
Cleanup needed - close (ie "delete") your old branches when you're done.  Branches are not repositories for your next change....get rid of them!!!

**Comment by ethan-max** [comment]
Not necessarily. After a merge, you might decide to continue working on that branch. In the course it talked about how orgs will often have a development branch that devs use instead of pushing things straight into master.

**Comment by melanietimms** [comment]
Do you mean a single development branch that is always left open?  It certainly is possible to reopen a branch even after deletion.
I heard that branches are also normally created for working on each issue too

**Comment by ethan-max** [comment]
Yeah. Oh well. It's not like we're gonna get marked on it. :man_shrugging:

**Comment by melanietimms** [comment]
True 💁‍♀️😉

**Comment by pawter2** [comment]
I missed class today, so I'm still catching up but I tentatively side with the sheep shagger.

**Comment by ethan-max** [comment]
We're both kiwi lol

**Comment by pawter2** [comment]
disgusting

**Comment by pawter2** [comment]
I am going to do what Melanie thinks is right and close this branch, for practice.
